// <auto-generated />
using System;
using Cascade_Backend_Developer_AssessmentTest.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cascade_Backend_Developer_AssessmentTest.Migrations
{
    [DbContext(typeof(BooksContext))]
    partial class BooksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Cascade_Backend_Developer_AssessmentTest.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AuthorFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleOfContainer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleOfSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VolumeNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorFirstName = "Wilder",
                            AuthorLastName = "Torres",
                            IssueNo = "February 1935",
                            Location = "pp. 120-126",
                            Price = 33.5m,
                            PublicationDate = new DateTime(2021, 12, 14, 23, 34, 26, 775, DateTimeKind.Local).AddTicks(5203),
                            Publisher = "GEEKULAR",
                            Title = "Testable book",
                            TitleOfContainer = "On Writing, Editing",
                            TitleOfSource = "Behind the Blue Pencil: Censorship: Cencorship?",
                            URL = "https://www.wikihow.com/images/9/90/Cite-Sources-in-Chicago-Manual-of-Style-Format-Step-26-Version-2.jpg",
                            VolumeNo = "2"
                        },
                        new
                        {
                            Id = 2,
                            AuthorFirstName = "Obrien",
                            AuthorLastName = "Goodman",
                            IssueNo = "February 1935",
                            Location = "pp. 120-126",
                            Price = 125.5m,
                            PublicationDate = new DateTime(2021, 12, 14, 23, 34, 26, 777, DateTimeKind.Local).AddTicks(9199),
                            Publisher = "VERBUS",
                            Title = "Being goog boy",
                            TitleOfContainer = "On Writing, Editing, and Publishing",
                            TitleOfSource = "Behind the Blue Pencil: Censorship: Cencorship?",
                            URL = "https://www.wikihow.com/images/9/90/Cite-Sources-in-Chicago-Manual-of-Style-Format-Step-26-Version-2.jpg",
                            VolumeNo = "2"
                        },
                        new
                        {
                            Id = 3,
                            AuthorFirstName = "Obrien",
                            AuthorLastName = "Goodman",
                            IssueNo = "February 1935",
                            Location = "pp. 120-126",
                            Price = 125.5m,
                            PublicationDate = new DateTime(2021, 12, 14, 23, 34, 26, 777, DateTimeKind.Local).AddTicks(9227),
                            Publisher = "VERBUS",
                            Title = "Being goog boy",
                            TitleOfContainer = "On Writing, Editing, and Publishing",
                            TitleOfSource = "Behind the Blue Pencil: Censorship: Cencorship?",
                            URL = "https://www.wikihow.com/images/9/90/Cite-Sources-in-Chicago-Manual-of-Style-Format-Step-26-Version-2.jpg",
                            VolumeNo = "2"
                        },
                        new
                        {
                            Id = 4,
                            AuthorFirstName = "Hello",
                            AuthorLastName = "Sadaf",
                            IssueNo = "February 1935",
                            Location = "pp. 120-126",
                            Price = 125.3m,
                            PublicationDate = new DateTime(2021, 12, 14, 23, 34, 26, 777, DateTimeKind.Local).AddTicks(9232),
                            Publisher = "Ahmet",
                            Title = "Being goog boy",
                            TitleOfContainer = "On Writing, Editing, and Publishing",
                            TitleOfSource = "Behind the Blue Pencil: Censorship: Cencorship?",
                            URL = "https://www.wikihow.com/images/9/90/Cite-Sources-in-Chicago-Manual-of-Style-Format-Step-26-Version-2.jpg",
                            VolumeNo = "2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
